SELECT * FROM file;
SELECT * FROM country;
SELECT * FROM genre;
SELECT * FROM "user";
SELECT * FROM person;
SELECT * FROM movie;
SELECT * FROM character;
SELECT * FROM movie_genre;
SELECT * FROM user_favorite_movie;